DEFS = {'architectures': {'create': {},
                   'destroy': {},
                   'index': {},
                   'show': {},
                   'update': {}},
 'audits': {'index': {}, 'show': {}},
 'auth_source_ldaps': {'create': {},
                       'destroy': {},
                       'index': {},
                       'show': {},
                       'update': {}},
 'bookmarks': {'create': {},
               'destroy': {},
               'index': {},
               'show': {},
               'update': {}},
 'common_parameters': {'create': {},
                       'destroy': {},
                       'index': {},
                       'show': {},
                       'update': {}},
 'compute_resources': {'create': {},
                       'destroy': {},
                       'index': {},
                       'show': {},
                       'update': {}},
 'config_templates': {'build_pxe_default': {},
                      'create': {},
                      'destroy': {},
                      'index': {},
                      'revision': {},
                      'show': {},
                      'update': {}},
 'dashboard': {'index': {}},
 'domains': {'create': {},
             'destroy': {},
             'index': {},
             'show': {},
             'update': {}},
 'environments': {'create': {},
                  'destroy': {},
                  'index': {},
                  'show': {},
                  'update': {}},
 'fact_values': {'index': {}},
 'home': {'index': {}, 'status': {}},
 'hostgroups': {'create': {},
                'destroy': {},
                'index': {},
                'show': {},
                'update': {}},
 'hosts': {'create': {},
           'destroy': {},
           'index': {},
           'show': {},
           'status': {},
           'update': {}},
 'images': {'create': {},
            'destroy': {},
            'index': {},
            'show': {},
            'update': {}},
 'lookup_keys': {'create': {},
                 'destroy': {},
                 'index': {},
                 'show': {},
                 'update': {}},
 'media': {'create': {}, 'destroy': {}, 'index': {}, 'show': {}, 'update': {}},
 'models': {'create': {},
            'destroy': {},
            'index': {},
            'show': {},
            'update': {}},
 'operatingsystems': {'bootfiles': {},
                      'create': {},
                      'destroy': {},
                      'index': {},
                      'show': {},
                      'update': {}},
 'ptables': {'create': {},
             'destroy': {},
             'index': {},
             'show': {},
             'update': {}},
 'puppetclasses': {'create': {},
                   'destroy': {},
                   'index': {},
                   'show': {},
                   'update': {}},
 'reports': {'destroy': {}, 'index': {}, 'last': {}, 'show': {}},
 'roles': {'create': {}, 'destroy': {}, 'index': {}, 'show': {}, 'update': {}},
 'settings': {'index': {}, 'show': {}, 'update': {}},
 'smart_proxies': {'create': {},
                   'destroy': {},
                   'index': {},
                   'show': {},
                   'update': {}},
 'subnets': {'create': {},
             'destroy': {},
             'index': {},
             'show': {},
             'update': {}},
 'template_kinds': {'index': {}},
 'usergroups': {'create': {},
                'destroy': {},
                'index': {},
                'show': {},
                'update': {}},
 'users': {'create': {}, 'destroy': {}, 'index': {}, 'show': {}, 'update': {}}}