DEFS = {'architectures': {'create': {'architecture ': {'ptype': 'Hash',
                                                'required': False},
                              'architecture[name] ': {'ptype': 'String',
                                                      'required': True},
                              'architecture[operatingsystem_ids] ': {'ptype': 'Array',
                                                                     'required': False}},
                   'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                       'required': True}},
                   'index': {'order ': {'ptype': 'String',
                                        'required': False},
                             'page ': {'ptype': 'String', 'required': False},
                             'per_page ': {'ptype': 'String',
                                           'required': False},
                             'search ': {'ptype': 'String',
                                         'required': False}},
                   'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                    'required': True}},
                   'update': {'architecture ': {'ptype': 'Hash',
                                                'required': False},
                              'architecture[name] ': {'ptype': 'String',
                                                      'required': False},
                              'architecture[operatingsystem_ids] ': {'ptype': 'Array',
                                                                     'required': False},
                              'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                      'required': True}}},
 'audits': {'index': {'order ': {'ptype': 'String', 'required': False},
                      'page ': {'ptype': 'String', 'required': False},
                      'per_page ': {'ptype': 'String', 'required': False},
                      'search ': {'ptype': 'String', 'required': False}},
            'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                             'required': True}}},
 'auth_source_ldaps': {'create': {'auth_source_ldap ': {'ptype': 'Hash',
                                                        'required': False},
                                  'auth_source_ldap[account] ': {'ptype': 'String',
                                                                 'required': False},
                                  'auth_source_ldap[account_password] ': {'ptype': 'String',
                                                                          'required': True},
                                  'auth_source_ldap[attr_firstname] ': {'ptype': 'String',
                                                                        'required': True},
                                  'auth_source_ldap[attr_lastname] ': {'ptype': 'String',
                                                                       'required': True},
                                  'auth_source_ldap[attr_login] ': {'ptype': 'String',
                                                                    'required': True},
                                  'auth_source_ldap[attr_mail] ': {'ptype': 'String',
                                                                   'required': True},
                                  'auth_source_ldap[base_dn] ': {'ptype': 'String',
                                                                 'required': False},
                                  'auth_source_ldap[host] ': {'ptype': 'String',
                                                              'required': True},
                                  'auth_source_ldap[name] ': {'ptype': 'String',
                                                              'required': True},
                                  'auth_source_ldap[onthefly_register] ': {'ptype': "'true' or 'false'",
                                                                           'required': False},
                                  'auth_source_ldap[port] ': {'ptype': 'number.',
                                                              'required': False},
                                  'auth_source_ldap[tls] ': {'ptype': "'true' or 'false'",
                                                             'required': False}},
                       'destroy': {'id ': {'ptype': 'String',
                                           'required': True}},
                       'index': {'page ': {'ptype': 'String',
                                           'required': False},
                                 'per_page ': {'ptype': 'String',
                                               'required': False}},
                       'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                        'required': True}},
                       'update': {'auth_source_ldap ': {'ptype': 'Hash',
                                                        'required': False},
                                  'auth_source_ldap[account] ': {'ptype': 'String',
                                                                 'required': False},
                                  'auth_source_ldap[account_password] ': {'ptype': 'String',
                                                                          'required': True},
                                  'auth_source_ldap[attr_firstname] ': {'ptype': 'String',
                                                                        'required': True},
                                  'auth_source_ldap[attr_lastname] ': {'ptype': 'String',
                                                                       'required': True},
                                  'auth_source_ldap[attr_login] ': {'ptype': 'String',
                                                                    'required': True},
                                  'auth_source_ldap[attr_mail] ': {'ptype': 'String',
                                                                   'required': True},
                                  'auth_source_ldap[base_dn] ': {'ptype': 'String',
                                                                 'required': False},
                                  'auth_source_ldap[host] ': {'ptype': 'String',
                                                              'required': False},
                                  'auth_source_ldap[name] ': {'ptype': 'String',
                                                              'required': False},
                                  'auth_source_ldap[onthefly_register] ': {'ptype': "'true' or 'false'",
                                                                           'required': False},
                                  'auth_source_ldap[port] ': {'ptype': 'number.',
                                                              'required': False},
                                  'auth_source_ldap[tls] ': {'ptype': "'true' or 'false'",
                                                             'required': False},
                                  'id ': {'ptype': 'String',
                                          'required': True}}},
 'autosign': {'index': {}},
 'bookmarks': {'create': {'bookmark ': {'ptype': 'Hash', 'required': False},
                          'bookmark[controller] ': {'ptype': 'String',
                                                    'required': True},
                          'bookmark[name] ': {'ptype': 'String',
                                              'required': True},
                          'bookmark[public] ': {'ptype': "'true' or 'false'",
                                                'required': False},
                          'bookmark[query] ': {'ptype': 'String',
                                               'required': True}},
               'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                   'required': True}},
               'index': {'page ': {'ptype': 'String', 'required': False},
                         'per_page ': {'ptype': 'String', 'required': False}},
               'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                'required': True}},
               'update': {'bookmark ': {'ptype': 'Hash', 'required': False},
                          'bookmark[controller] ': {'ptype': 'String',
                                                    'required': False},
                          'bookmark[name] ': {'ptype': 'String',
                                              'required': False},
                          'bookmark[public] ': {'ptype': "'true' or 'false'",
                                                'required': False},
                          'bookmark[query] ': {'ptype': 'String',
                                               'required': False},
                          'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                  'required': True}}},
 'common_parameters': {'create': {'common_parameter ': {'ptype': 'Hash',
                                                        'required': False},
                                  'common_parameter[name] ': {'ptype': 'String',
                                                              'required': True},
                                  'common_parameter[value] ': {'ptype': 'String',
                                                               'required': True}},
                       'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                           'required': True}},
                       'index': {'order ': {'ptype': 'String',
                                            'required': False},
                                 'page ': {'ptype': 'String',
                                           'required': False},
                                 'per_page ': {'ptype': 'String',
                                               'required': False},
                                 'search ': {'ptype': 'String',
                                             'required': False}},
                       'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                        'required': True}},
                       'update': {'common_parameter ': {'ptype': 'Hash',
                                                        'required': False},
                                  'common_parameter[name] ': {'ptype': 'String',
                                                              'required': False},
                                  'common_parameter[value] ': {'ptype': 'String',
                                                               'required': False},
                                  'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                          'required': True}}},
 'compute_resources': {'available_images': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                    'required': True}},
                       'create': {'compute_resource ': {'ptype': 'Hash',
                                                        'required': False},
                                  'compute_resource[description] ': {'ptype': 'String',
                                                                     'required': False},
                                  'compute_resource[name] ': {'ptype': 'String',
                                                              'required': False},
                                  'compute_resource[password] ': {'ptype': 'String',
                                                                  'required': False},
                                  'compute_resource[provider] ': {'ptype': 'String',
                                                                  'required': False},
                                  'compute_resource[region] ': {'ptype': 'String',
                                                                'required': False},
                                  'compute_resource[server] ': {'ptype': 'String',
                                                                'required': False},
                                  'compute_resource[tenant] ': {'ptype': 'String',
                                                                'required': False},
                                  'compute_resource[url] ': {'ptype': 'String',
                                                             'required': True},
                                  'compute_resource[user] ': {'ptype': 'String',
                                                              'required': False},
                                  'compute_resource[uuid] ': {'ptype': 'String',
                                                              'required': False}},
                       'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                           'required': True}},
                       'index': {'order ': {'ptype': 'String',
                                            'required': False},
                                 'page ': {'ptype': 'String',
                                           'required': False},
                                 'per_page ': {'ptype': 'String',
                                               'required': False},
                                 'search ': {'ptype': 'String',
                                             'required': False}},
                       'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                        'required': True}},
                       'update': {'compute_resource ': {'ptype': 'Hash',
                                                        'required': False},
                                  'compute_resource[description] ': {'ptype': 'String',
                                                                     'required': False},
                                  'compute_resource[name] ': {'ptype': 'String',
                                                              'required': False},
                                  'compute_resource[password] ': {'ptype': 'String',
                                                                  'required': False},
                                  'compute_resource[provider] ': {'ptype': 'String',
                                                                  'required': False},
                                  'compute_resource[region] ': {'ptype': 'String',
                                                                'required': False},
                                  'compute_resource[server] ': {'ptype': 'String',
                                                                'required': False},
                                  'compute_resource[tenant] ': {'ptype': 'String',
                                                                'required': False},
                                  'compute_resource[url] ': {'ptype': 'String',
                                                             'required': False},
                                  'compute_resource[user] ': {'ptype': 'String',
                                                              'required': False},
                                  'compute_resource[uuid] ': {'ptype': 'String',
                                                              'required': False},
                                  'id ': {'ptype': 'String',
                                          'required': True}}},
 'config_templates': {'build_pxe_default': {},
                      'create': {'config_template ': {'ptype': 'Hash',
                                                      'required': False},
                                 'config_template[audit_comment] ': {'ptype': 'String',
                                                                     'required': False},
                                 'config_template[name] ': {'ptype': 'String',
                                                            'required': True},
                                 'config_template[operatingsystem_ids] ': {'ptype': 'Array',
                                                                           'required': False},
                                 'config_template[snippet] ': {'ptype': "'true' or 'false'",
                                                               'required': False},
                                 'config_template[template] ': {'ptype': 'String',
                                                                'required': True},
                                 'config_template[template_combinations_attributes] ': {'ptype': 'Array',
                                                                                        'required': False},
                                 'config_template[template_kind_id] ': {'ptype': 'number.',
                                                                        'required': False}},
                      'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                          'required': True}},
                      'index': {'order ': {'ptype': 'String',
                                           'required': False},
                                'page ': {'ptype': 'String',
                                          'required': False},
                                'per_page ': {'ptype': 'String',
                                              'required': False},
                                'search ': {'ptype': 'String',
                                            'required': False}},
                      'revision': {'version ': {'ptype': 'String',
                                                'required': False}},
                      'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                       'required': True}},
                      'update': {'config_template ': {'ptype': 'Hash',
                                                      'required': False},
                                 'config_template[audit_comment] ': {'ptype': 'String',
                                                                     'required': False},
                                 'config_template[name] ': {'ptype': 'String',
                                                            'required': False},
                                 'config_template[operatingsystem_ids] ': {'ptype': 'Array',
                                                                           'required': False},
                                 'config_template[snippet] ': {'ptype': "'true' or 'false'",
                                                               'required': False},
                                 'config_template[template] ': {'ptype': 'String',
                                                                'required': False},
                                 'config_template[template_combinations_attributes] ': {'ptype': 'Array',
                                                                                        'required': False},
                                 'config_template[template_kind_id] ': {'ptype': 'number.',
                                                                        'required': False},
                                 'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                         'required': True}}},
 'dashboard': {'index': {'search ': {'ptype': 'String', 'required': False}}},
 'domains': {'create': {'domain ': {'ptype': 'Hash', 'required': False},
                        'domain[dns_id] ': {'ptype': 'number.',
                                            'required': False},
                        'domain[domain_parameters_attributes] ': {'ptype': 'Array',
                                                                  'required': False},
                        'domain[fullname] ': {'ptype': 'String',
                                              'required': False},
                        'domain[name] ': {'ptype': 'String',
                                          'required': True}},
             'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                 'required': True}},
             'index': {'order ': {'ptype': 'String', 'required': False},
                       'page ': {'ptype': 'String', 'required': False},
                       'per_page ': {'ptype': 'String', 'required': False},
                       'search ': {'ptype': 'String', 'required': False}},
             'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                              'required': True}},
             'update': {'domain ': {'ptype': 'Hash', 'required': False},
                        'domain[dns_id] ': {'ptype': 'number.',
                                            'required': False},
                        'domain[domain_parameters_attributes] ': {'ptype': 'Array',
                                                                  'required': False},
                        'domain[fullname] ': {'ptype': 'String',
                                              'required': False},
                        'domain[name] ': {'ptype': 'String',
                                          'required': False},
                        'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                'required': True}}},
 'environments': {'create': {'environment ': {'ptype': 'Hash',
                                              'required': False},
                             'environment[name] ': {'ptype': 'String',
                                                    'required': True}},
                  'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                      'required': True}},
                  'import_puppetclasses': {'dryrun ': {'ptype': "'true' or 'false'",
                                                       'required': False},
                                           'environment_id ': {'ptype': 'String',
                                                               'required': False},
                                           'except ': {'ptype': 'String',
                                                       'required': False},
                                           'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                   'required': True},
                                           'smart_proxy_id ': {'ptype': 'String',
                                                               'required': False}},
                  'index': {'order ': {'ptype': 'String', 'required': False},
                            'page ': {'ptype': 'String', 'required': False},
                            'per_page ': {'ptype': 'String',
                                          'required': False},
                            'search ': {'ptype': 'String',
                                        'required': False}},
                  'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                   'required': True}},
                  'update': {'environment ': {'ptype': 'Hash',
                                              'required': False},
                             'environment[name] ': {'ptype': 'String',
                                                    'required': False},
                             'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                     'required': True}}},
 'fact_values': {'index': {'order ': {'ptype': 'String', 'required': False},
                           'page ': {'ptype': 'String', 'required': False},
                           'per_page ': {'ptype': 'String',
                                         'required': False},
                           'search ': {'ptype': 'String', 'required': False}}},
 'home': {'index': {}, 'status': {}},
 'host_classes': {'create': {'host_id ': {'ptype': 'String',
                                          'required': True},
                             'puppetclass_id ': {'ptype': 'String',
                                                 'required': True}},
                  'destroy': {'host_id ': {'ptype': 'String',
                                           'required': True},
                              'id ': {'ptype': 'String', 'required': True}},
                  'index': {}},
 'hostgroup_classes': {'create': {'hostgroup_id ': {'ptype': 'String',
                                                    'required': True},
                                  'puppetclass_id ': {'ptype': 'String',
                                                      'required': True}},
                       'destroy': {'hostgroup_id ': {'ptype': 'String',
                                                     'required': True},
                                   'id ': {'ptype': 'String',
                                           'required': True}},
                       'index': {}},
 'hostgroups': {'create': {'hostgroup ': {'ptype': 'Hash',
                                          'required': False},
                           'hostgroup[architecture_id] ': {'ptype': 'number.',
                                                           'required': False},
                           'hostgroup[domain_id] ': {'ptype': 'number.',
                                                     'required': False},
                           'hostgroup[environment_id] ': {'ptype': 'number.',
                                                          'required': False},
                           'hostgroup[medium_id] ': {'ptype': 'number.',
                                                     'required': False},
                           'hostgroup[name] ': {'ptype': 'String',
                                                'required': True},
                           'hostgroup[operatingsystem_id] ': {'ptype': 'number.',
                                                              'required': False},
                           'hostgroup[parent_id] ': {'ptype': 'number.',
                                                     'required': False},
                           'hostgroup[ptable_id] ': {'ptype': 'number.',
                                                     'required': False},
                           'hostgroup[puppet_ca_proxy_id] ': {'ptype': 'number.',
                                                              'required': False},
                           'hostgroup[puppet_proxy_id] ': {'ptype': 'number.',
                                                           'required': False},
                           'hostgroup[subnet_id] ': {'ptype': 'number.',
                                                     'required': False}},
                'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                    'required': True}},
                'index': {'order ': {'ptype': 'String', 'required': False},
                          'page ': {'ptype': 'String', 'required': False},
                          'per_page ': {'ptype': 'String',
                                        'required': False},
                          'search ': {'ptype': 'String', 'required': False}},
                'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                 'required': True}},
                'update': {'hostgroup ': {'ptype': 'Hash',
                                          'required': False},
                           'hostgroup[architecture_id] ': {'ptype': 'number.',
                                                           'required': False},
                           'hostgroup[domain_id] ': {'ptype': 'number.',
                                                     'required': False},
                           'hostgroup[environment_id] ': {'ptype': 'number.',
                                                          'required': False},
                           'hostgroup[medium_id] ': {'ptype': 'number.',
                                                     'required': False},
                           'hostgroup[name] ': {'ptype': 'String',
                                                'required': False},
                           'hostgroup[operatingsystem_id] ': {'ptype': 'number.',
                                                              'required': False},
                           'hostgroup[parent_id] ': {'ptype': 'number.',
                                                     'required': False},
                           'hostgroup[ptable_id] ': {'ptype': 'number.',
                                                     'required': False},
                           'hostgroup[puppet_ca_proxy_id] ': {'ptype': 'number.',
                                                              'required': False},
                           'hostgroup[puppet_proxy_id] ': {'ptype': 'number.',
                                                           'required': False},
                           'hostgroup[subnet_id] ': {'ptype': 'number.',
                                                     'required': False},
                           'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                   'required': True}}},
 'hosts': {'boot': {'device ': {'ptype': 'String', 'required': True},
                    'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, dot(.), space, underscore(_), hypen(-) with no leading or trailing space.',
                            'required': True}},
           'create': {'host ': {'ptype': 'Hash', 'required': False},
                      'host[architecture_id] ': {'ptype': 'number.',
                                                 'required': False},
                      'host[build] ': {'ptype': "'true' or 'false'",
                                       'required': False},
                      'host[capabilities] ': {'ptype': 'String',
                                              'required': False},
                      'host[compute_attributes] ': {'ptype': 'Hash',
                                                    'required': False},
                      'host[compute_resource_id] ': {'ptype': 'number.',
                                                     'required': False},
                      'host[domain_id] ': {'ptype': 'number.',
                                           'required': False},
                      'host[enabled] ': {'ptype': "'true' or 'false'",
                                         'required': False},
                      'host[environment_id] ': {'ptype': 'String',
                                                'required': False},
                      'host[host_parameters_attributes] ': {'ptype': 'Array',
                                                            'required': False},
                      'host[hostgroup_id] ': {'ptype': 'number.',
                                              'required': False},
                      'host[image_id] ': {'ptype': 'number.',
                                          'required': False},
                      'host[ip] ': {'ptype': 'String', 'required': True},
                      'host[mac] ': {'ptype': 'String', 'required': True},
                      'host[managed] ': {'ptype': "'true' or 'false'",
                                         'required': False},
                      'host[medium_id] ': {'ptype': 'number.',
                                           'required': False},
                      'host[model_id] ': {'ptype': 'number.',
                                          'required': False},
                      'host[name] ': {'ptype': 'String', 'required': True},
                      'host[operatingsystem_id] ': {'ptype': 'String',
                                                    'required': False},
                      'host[owner_id] ': {'ptype': 'number.',
                                          'required': False},
                      'host[progress_report_id] ': {'ptype': 'String',
                                                    'required': False},
                      'host[provision_method] ': {'ptype': 'String',
                                                  'required': False},
                      'host[ptable_id] ': {'ptype': 'number.',
                                           'required': False},
                      'host[puppet_ca_proxy_id] ': {'ptype': 'number.',
                                                    'required': False},
                      'host[puppet_class_ids] ': {'ptype': 'Array',
                                                  'required': False},
                      'host[puppet_proxy_id] ': {'ptype': 'number.',
                                                 'required': False},
                      'host[sp_subnet_id] ': {'ptype': 'number.',
                                              'required': False},
                      'host[subnet_id] ': {'ptype': 'number.',
                                           'required': False}},
           'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                               'required': True}},
           'facts': {'certname ': {'ptype': 'String', 'required': False},
                     'facts ': {'ptype': 'Hash', 'required': True},
                     'name ': {'ptype': 'String', 'required': True},
                     'type ': {'ptype': 'String', 'required': False}},
           'index': {'order ': {'ptype': 'String', 'required': False},
                     'page ': {'ptype': 'String', 'required': False},
                     'per_page ': {'ptype': 'String', 'required': False},
                     'search ': {'ptype': 'String', 'required': False}},
           'power': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, dot(.), space, underscore(_), hypen(-) with no leading or trailing space.',
                             'required': True},
                     'power_action ': {'ptype': 'String', 'required': True}},
           'puppetrun': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, dot(.), space, underscore(_), hypen(-) with no leading or trailing space.',
                                 'required': True}},
           'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, dot(.), space, underscore(_), hypen(-) with no leading or trailing space.',
                            'required': True}},
           'status': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, dot(.), space, underscore(_), hypen(-) with no leading or trailing space.',
                              'required': True}},
           'update': {'host ': {'ptype': 'Hash', 'required': False},
                      'host[architecture_id] ': {'ptype': 'number.',
                                                 'required': False},
                      'host[build] ': {'ptype': "'true' or 'false'",
                                       'required': False},
                      'host[capabilities] ': {'ptype': 'String',
                                              'required': False},
                      'host[compute_attributes] ': {'ptype': 'Hash',
                                                    'required': False},
                      'host[compute_resource_id] ': {'ptype': 'number.',
                                                     'required': False},
                      'host[domain_id] ': {'ptype': 'number.',
                                           'required': False},
                      'host[enabled] ': {'ptype': "'true' or 'false'",
                                         'required': False},
                      'host[environment_id] ': {'ptype': 'String',
                                                'required': False},
                      'host[host_parameters_attributes] ': {'ptype': 'Array',
                                                            'required': False},
                      'host[hostgroup_id] ': {'ptype': 'number.',
                                              'required': False},
                      'host[image_id] ': {'ptype': 'number.',
                                          'required': False},
                      'host[ip] ': {'ptype': 'String', 'required': True},
                      'host[mac] ': {'ptype': 'String', 'required': True},
                      'host[managed] ': {'ptype': "'true' or 'false'",
                                         'required': False},
                      'host[medium_id] ': {'ptype': 'number.',
                                           'required': False},
                      'host[model_id] ': {'ptype': 'number.',
                                          'required': False},
                      'host[name] ': {'ptype': 'String', 'required': False},
                      'host[operatingsystem_id] ': {'ptype': 'String',
                                                    'required': False},
                      'host[owner_id] ': {'ptype': 'number.',
                                          'required': False},
                      'host[progress_report_id] ': {'ptype': 'String',
                                                    'required': False},
                      'host[provision_method] ': {'ptype': 'String',
                                                  'required': False},
                      'host[ptable_id] ': {'ptype': 'number.',
                                           'required': False},
                      'host[puppet_ca_proxy_id] ': {'ptype': 'number.',
                                                    'required': False},
                      'host[puppet_class_ids] ': {'ptype': 'Array',
                                                  'required': False},
                      'host[puppet_proxy_id] ': {'ptype': 'number.',
                                                 'required': False},
                      'host[sp_subnet_id] ': {'ptype': 'number.',
                                              'required': False},
                      'host[subnet_id] ': {'ptype': 'number.',
                                           'required': False},
                      'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                              'required': True}}},
 'images': {'create': {'compute_resource_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                'required': True},
                       'image ': {'ptype': 'Hash', 'required': False},
                       'image[architecture_id] ': {'ptype': 'number.',
                                                   'required': True},
                       'image[compute_resource_id] ': {'ptype': 'number.',
                                                       'required': True},
                       'image[name] ': {'ptype': 'String', 'required': True},
                       'image[operatingsystem_id] ': {'ptype': 'number.',
                                                      'required': True},
                       'image[username] ': {'ptype': 'String',
                                            'required': True},
                       'image[uuid] ': {'ptype': 'String', 'required': True}},
            'destroy': {'compute_resource_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                 'required': True},
                        'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                'required': True}},
            'index': {'compute_resource_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                               'required': True},
                      'order ': {'ptype': 'String', 'required': False},
                      'page ': {'ptype': 'String', 'required': False},
                      'per_page ': {'ptype': 'String', 'required': False},
                      'search ': {'ptype': 'String', 'required': False}},
            'show': {'compute_resource_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                              'required': True},
                     'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                             'required': True}},
            'update': {'compute_resource_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                'required': True},
                       'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                               'required': True},
                       'image ': {'ptype': 'Hash', 'required': False},
                       'image[architecture_id] ': {'ptype': 'number.',
                                                   'required': False},
                       'image[compute_resource_id] ': {'ptype': 'number.',
                                                       'required': False},
                       'image[name] ': {'ptype': 'String',
                                        'required': False},
                       'image[operatingsystem_id] ': {'ptype': 'number.',
                                                      'required': False},
                       'image[username] ': {'ptype': 'String',
                                            'required': False},
                       'image[uuid] ': {'ptype': 'String',
                                        'required': False}}},
 'interfaces': {'create': {'host_id ': {'ptype': 'String', 'required': True},
                           'interface ': {'ptype': 'Hash',
                                          'required': False},
                           'interface[domain_id] ': {'ptype': 'Fixnum',
                                                     'required': False},
                           'interface[ip] ': {'ptype': 'String',
                                              'required': True},
                           'interface[mac] ': {'ptype': 'String',
                                               'required': True},
                           'interface[name] ': {'ptype': 'String',
                                                'required': True},
                           'interface[password] ': {'ptype': 'String',
                                                    'required': False},
                           'interface[provider] ': {'ptype': 'String',
                                                    'required': False},
                           'interface[subnet_id] ': {'ptype': 'Fixnum',
                                                     'required': False},
                           'interface[type] ': {'ptype': 'String',
                                                'required': True},
                           'interface[username] ': {'ptype': 'String',
                                                    'required': False}},
                'destroy': {'id ': {'ptype': 'String', 'required': True}},
                'index': {'host_id ': {'ptype': 'String', 'required': True}},
                'show': {'host_id ': {'ptype': 'String', 'required': True},
                         'id ': {'ptype': 'String', 'required': True}},
                'update': {'host_id ': {'ptype': 'String', 'required': True},
                           'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                   'required': True},
                           'interface ': {'ptype': 'Hash',
                                          'required': False},
                           'interface[domain_id] ': {'ptype': 'Fixnum',
                                                     'required': False},
                           'interface[ip] ': {'ptype': 'String',
                                              'required': False},
                           'interface[mac] ': {'ptype': 'String',
                                               'required': False},
                           'interface[name] ': {'ptype': 'String',
                                                'required': False},
                           'interface[password] ': {'ptype': 'String',
                                                    'required': False},
                           'interface[provider] ': {'ptype': 'String',
                                                    'required': False},
                           'interface[subnet_id] ': {'ptype': 'Fixnum',
                                                     'required': False},
                           'interface[type] ': {'ptype': 'String',
                                                'required': False},
                           'interface[username] ': {'ptype': 'String',
                                                    'required': False}}},
 'locations': {'create': {'location ': {'ptype': 'Hash', 'required': False},
                          'location[name] ': {'ptype': 'String',
                                              'required': True}},
               'destroy': {},
               'index': {'order ': {'ptype': 'String', 'required': False},
                         'page ': {'ptype': 'String', 'required': False},
                         'per_page ': {'ptype': 'String', 'required': False},
                         'search ': {'ptype': 'String', 'required': False}},
               'show': {},
               'update': {'location ': {'ptype': 'Hash', 'required': False},
                          'location[name] ': {'ptype': 'String',
                                              'required': False}}},
 'media': {'create': {'medium ': {'ptype': 'Hash', 'required': False},
                      'medium[name] ': {'ptype': 'String', 'required': True},
                      'medium[operatingsystem_ids] ': {'ptype': 'Array',
                                                       'required': False},
                      'medium[os_family] ': {'ptype': 'String',
                                             'required': False},
                      'medium[path] ': {'ptype': 'String', 'required': True}},
           'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                               'required': True}},
           'index': {'order ': {'ptype': 'String', 'required': False},
                     'page ': {'ptype': 'String', 'required': False},
                     'per_page ': {'ptype': 'String', 'required': False},
                     'search ': {'ptype': 'String', 'required': False}},
           'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                            'required': True}},
           'update': {'id ': {'ptype': 'String', 'required': True},
                      'medium ': {'ptype': 'Hash', 'required': False},
                      'medium[name] ': {'ptype': 'String',
                                        'required': False},
                      'medium[operatingsystem_ids] ': {'ptype': 'Array',
                                                       'required': False},
                      'medium[os_family] ': {'ptype': 'String',
                                             'required': False},
                      'medium[path] ': {'ptype': 'String',
                                        'required': False}}},
 'models': {'create': {'model ': {'ptype': 'Hash', 'required': False},
                       'model[hardware_model] ': {'ptype': 'String',
                                                  'required': False},
                       'model[info] ': {'ptype': 'String',
                                        'required': False},
                       'model[name] ': {'ptype': 'String', 'required': True},
                       'model[vendor_class] ': {'ptype': 'String',
                                                'required': False}},
            'destroy': {'id ': {'ptype': 'String', 'required': True}},
            'index': {'order ': {'ptype': 'String', 'required': False},
                      'page ': {'ptype': 'String', 'required': False},
                      'per_page ': {'ptype': 'String', 'required': False},
                      'search ': {'ptype': 'String', 'required': False}},
            'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                             'required': True}},
            'update': {'id ': {'ptype': 'String', 'required': True},
                       'model ': {'ptype': 'Hash', 'required': False},
                       'model[hardware_model] ': {'ptype': 'String',
                                                  'required': False},
                       'model[info] ': {'ptype': 'String',
                                        'required': False},
                       'model[name] ': {'ptype': 'String',
                                        'required': False},
                       'model[vendor_class] ': {'ptype': 'String',
                                                'required': False}}},
 'operatingsystems': {'bootfiles': {'architecture ': {'ptype': 'String',
                                                      'required': False},
                                    'id ': {'ptype': 'String',
                                            'required': True},
                                    'medium ': {'ptype': 'String',
                                                'required': False}},
                      'create': {'operatingsystem ': {'ptype': 'Hash',
                                                      'required': False},
                                 'operatingsystem[description] ': {'ptype': 'String',
                                                                   'required': False},
                                 'operatingsystem[family] ': {'ptype': 'String',
                                                              'required': False},
                                 'operatingsystem[major] ': {'ptype': 'String',
                                                             'required': True},
                                 'operatingsystem[minor] ': {'ptype': 'String',
                                                             'required': True},
                                 'operatingsystem[name] ': {'ptype': 'regular expression /\\A(\\S+)\\Z/.',
                                                            'required': True},
                                 'operatingsystem[release_name] ': {'ptype': 'String',
                                                                    'required': False}},
                      'destroy': {'id ': {'ptype': 'String',
                                          'required': True}},
                      'index': {'order ': {'ptype': 'String',
                                           'required': False},
                                'page ': {'ptype': 'String',
                                          'required': False},
                                'per_page ': {'ptype': 'String',
                                              'required': False},
                                'search ': {'ptype': 'String',
                                            'required': False}},
                      'show': {'id ': {'ptype': 'String', 'required': True}},
                      'update': {'id ': {'ptype': 'String',
                                         'required': True},
                                 'operatingsystem ': {'ptype': 'Hash',
                                                      'required': False},
                                 'operatingsystem[description] ': {'ptype': 'String',
                                                                   'required': False},
                                 'operatingsystem[family] ': {'ptype': 'String',
                                                              'required': False},
                                 'operatingsystem[major] ': {'ptype': 'String',
                                                             'required': False},
                                 'operatingsystem[minor] ': {'ptype': 'String',
                                                             'required': False},
                                 'operatingsystem[name] ': {'ptype': 'regular expression /\\A(\\S+)\\Z/.',
                                                            'required': False},
                                 'operatingsystem[release_name] ': {'ptype': 'String',
                                                                    'required': False}}},
 'organizations': {'create': {'organization ': {'ptype': 'Hash',
                                                'required': False},
                              'organization[name] ': {'ptype': 'String',
                                                      'required': True}},
                   'destroy': {},
                   'index': {'order ': {'ptype': 'String',
                                        'required': False},
                             'page ': {'ptype': 'String', 'required': False},
                             'per_page ': {'ptype': 'String',
                                           'required': False},
                             'search ': {'ptype': 'String',
                                         'required': False}},
                   'show': {},
                   'update': {'organization ': {'ptype': 'Hash',
                                                'required': False},
                              'organization[name] ': {'ptype': 'String',
                                                      'required': False}}},
 'os_default_templates': {'create': {'operatingsystem_id ': {'ptype': 'String',
                                                             'required': False},
                                     'os_default_template ': {'ptype': 'Hash',
                                                              'required': False},
                                     'os_default_template[config_template_id] ': {'ptype': 'number.',
                                                                                  'required': False},
                                     'os_default_template[template_kind_id] ': {'ptype': 'number.',
                                                                                'required': False}},
                          'destroy': {'id ': {'ptype': 'String',
                                              'required': True},
                                      'operatingsystem_id ': {'ptype': 'String',
                                                              'required': False}},
                          'index': {'operatingsystem_id ': {'ptype': 'String',
                                                            'required': False},
                                    'page ': {'ptype': 'String',
                                              'required': False},
                                    'per_page ': {'ptype': 'String',
                                                  'required': False}},
                          'show': {'id ': {'ptype': 'number.',
                                           'required': True},
                                   'operatingsystem_id ': {'ptype': 'String',
                                                           'required': False}},
                          'update': {'id ': {'ptype': 'String',
                                             'required': True},
                                     'operatingsystem_id ': {'ptype': 'String',
                                                             'required': False},
                                     'os_default_template ': {'ptype': 'Hash',
                                                              'required': False},
                                     'os_default_template[config_template_id] ': {'ptype': 'number.',
                                                                                  'required': False},
                                     'os_default_template[template_kind_id] ': {'ptype': 'number.',
                                                                                'required': False}}},
 'override_values': {'create': {'override_value ': {'ptype': 'Hash',
                                                    'required': False},
                                'override_value[match] ': {'ptype': 'String',
                                                           'required': False},
                                'override_value[value] ': {'ptype': 'String',
                                                           'required': False},
                                'smart_variable_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                       'required': False}},
                     'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                         'required': True}},
                     'index': {'page ': {'ptype': 'String',
                                         'required': False},
                               'per_page ': {'ptype': 'String',
                                             'required': False},
                               'smart_class_parameter_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                             'required': False},
                               'smart_variable_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                      'required': False}},
                     'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                      'required': True},
                              'smart_class_parameter_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                            'required': False},
                              'smart_variable_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                     'required': False}},
                     'update': {'override_value ': {'ptype': 'Hash',
                                                    'required': False},
                                'override_value[match] ': {'ptype': 'String',
                                                           'required': False},
                                'override_value[value] ': {'ptype': 'String',
                                                           'required': False}}},
 'parameters': {'create': {'domain_id ': {'ptype': 'String',
                                          'required': False},
                           'host_id ': {'ptype': 'String',
                                        'required': False},
                           'hostgroup_id ': {'ptype': 'String',
                                             'required': False},
                           'location_id ': {'ptype': 'String',
                                            'required': False},
                           'operatingsystem_id ': {'ptype': 'String',
                                                   'required': False},
                           'organization_id ': {'ptype': 'String',
                                                'required': False},
                           'parameter ': {'ptype': 'Hash',
                                          'required': False},
                           'parameter[name] ': {'ptype': 'String',
                                                'required': True},
                           'parameter[value] ': {'ptype': 'String',
                                                 'required': True}},
                'destroy': {'domain_id ': {'ptype': 'String',
                                           'required': False},
                            'host_id ': {'ptype': 'String',
                                         'required': False},
                            'hostgroup_id ': {'ptype': 'String',
                                              'required': False},
                            'id ': {'ptype': 'String', 'required': True},
                            'location_id ': {'ptype': 'String',
                                             'required': False},
                            'operatingsystem_id ': {'ptype': 'String',
                                                    'required': False},
                            'organization_id ': {'ptype': 'String',
                                                 'required': False}},
                'index': {'domain_id ': {'ptype': 'String',
                                         'required': False},
                          'host_id ': {'ptype': 'String', 'required': False},
                          'hostgroup_id ': {'ptype': 'String',
                                            'required': False},
                          'location_id ': {'ptype': 'String',
                                           'required': False},
                          'operatingsystem_id ': {'ptype': 'String',
                                                  'required': False},
                          'organization_id ': {'ptype': 'String',
                                               'required': False},
                          'page ': {'ptype': 'String', 'required': False},
                          'per_page ': {'ptype': 'String',
                                        'required': False}},
                'reset': {'domain_id ': {'ptype': 'String',
                                         'required': False},
                          'host_id ': {'ptype': 'String', 'required': False},
                          'hostgroup_id ': {'ptype': 'String',
                                            'required': False},
                          'location_id ': {'ptype': 'String',
                                           'required': False},
                          'operatingsystem_id ': {'ptype': 'String',
                                                  'required': False},
                          'organization_id ': {'ptype': 'String',
                                               'required': False}},
                'show': {'domain_id ': {'ptype': 'String',
                                        'required': False},
                         'host_id ': {'ptype': 'String', 'required': False},
                         'hostgroup_id ': {'ptype': 'String',
                                           'required': False},
                         'id ': {'ptype': 'String', 'required': True},
                         'location_id ': {'ptype': 'String',
                                          'required': False},
                         'operatingsystem_id ': {'ptype': 'String',
                                                 'required': False},
                         'organization_id ': {'ptype': 'String',
                                              'required': False}},
                'update': {'domain_id ': {'ptype': 'String',
                                          'required': False},
                           'host_id ': {'ptype': 'String',
                                        'required': False},
                           'hostgroup_id ': {'ptype': 'String',
                                             'required': False},
                           'id ': {'ptype': 'String', 'required': True},
                           'location_id ': {'ptype': 'String',
                                            'required': False},
                           'operatingsystem_id ': {'ptype': 'String',
                                                   'required': False},
                           'organization_id ': {'ptype': 'String',
                                                'required': False},
                           'parameter ': {'ptype': 'Hash',
                                          'required': False},
                           'parameter[name] ': {'ptype': 'String',
                                                'required': False},
                           'parameter[value] ': {'ptype': 'String',
                                                 'required': False}}},
 'plugins': {'index': {}},
 'ptables': {'create': {'ptable ': {'ptype': 'Hash', 'required': False},
                        'ptable[layout] ': {'ptype': 'String',
                                            'required': True},
                        'ptable[name] ': {'ptype': 'String',
                                          'required': True},
                        'ptable[os_family] ': {'ptype': 'String',
                                               'required': False}},
             'destroy': {'id ': {'ptype': 'String', 'required': True}},
             'index': {'order ': {'ptype': 'String', 'required': False},
                       'page ': {'ptype': 'String', 'required': False},
                       'per_page ': {'ptype': 'String', 'required': False},
                       'search ': {'ptype': 'String', 'required': False}},
             'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                              'required': True}},
             'update': {'id ': {'ptype': 'String', 'required': True},
                        'ptable ': {'ptype': 'Hash', 'required': False},
                        'ptable[layout] ': {'ptype': 'String',
                                            'required': False},
                        'ptable[name] ': {'ptype': 'String',
                                          'required': False},
                        'ptable[os_family] ': {'ptype': 'String',
                                               'required': False}}},
 'puppetclasses': {'create': {'puppetclass ': {'ptype': 'Hash',
                                               'required': False},
                              'puppetclass[name] ': {'ptype': 'String',
                                                     'required': True}},
                   'destroy': {'id ': {'ptype': 'String', 'required': True}},
                   'index': {'environment_id ': {'ptype': 'String',
                                                 'required': False},
                             'host_id ': {'ptype': 'String',
                                          'required': False},
                             'hostgroup_id ': {'ptype': 'String',
                                               'required': False},
                             'order ': {'ptype': 'String',
                                        'required': False},
                             'page ': {'ptype': 'String', 'required': False},
                             'per_page ': {'ptype': 'String',
                                           'required': False},
                             'search ': {'ptype': 'String',
                                         'required': False}},
                   'show': {'environment_id ': {'ptype': 'String',
                                                'required': False},
                            'host_id ': {'ptype': 'String',
                                         'required': False},
                            'hostgroup_id ': {'ptype': 'String',
                                              'required': False},
                            'id ': {'ptype': 'String', 'required': True}},
                   'update': {'id ': {'ptype': 'String', 'required': True},
                              'puppetclass ': {'ptype': 'Hash',
                                               'required': False},
                              'puppetclass[name] ': {'ptype': 'String',
                                                     'required': False}}},
 'reports': {'create': {'report ': {'ptype': 'Hash', 'required': False},
                        'report[host] ': {'ptype': 'String',
                                          'required': True},
                        'report[logs] ': {'ptype': 'Array',
                                          'required': False},
                        'report[metrics] ': {'ptype': 'Hash',
                                             'required': True},
                        'report[reported_at] ': {'ptype': 'String',
                                                 'required': True},
                        'report[status] ': {'ptype': 'Hash',
                                            'required': True}},
             'destroy': {'id ': {'ptype': 'String', 'required': True}},
             'index': {'order ': {'ptype': 'String', 'required': False},
                       'page ': {'ptype': 'String', 'required': False},
                       'per_page ': {'ptype': 'String', 'required': False},
                       'search ': {'ptype': 'String', 'required': False}},
             'last': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                              'required': True}},
             'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                              'required': True}}},
 'roles': {'create': {'role ': {'ptype': 'Hash', 'required': False},
                      'role[name] ': {'ptype': 'String', 'required': True}},
           'destroy': {'id ': {'ptype': 'String', 'required': True}},
           'index': {'page ': {'ptype': 'String', 'required': False},
                     'per_page ': {'ptype': 'String', 'required': False}},
           'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                            'required': True}},
           'update': {'id ': {'ptype': 'String', 'required': True},
                      'role ': {'ptype': 'Hash', 'required': False},
                      'role[name] ': {'ptype': 'String', 'required': False}}},
 'settings': {'index': {'order ': {'ptype': 'String', 'required': False},
                        'page ': {'ptype': 'String', 'required': False},
                        'per_page ': {'ptype': 'String', 'required': False},
                        'search ': {'ptype': 'String', 'required': False}},
              'show': {'id ': {'ptype': 'String', 'required': True}},
              'update': {'id ': {'ptype': 'String', 'required': True},
                         'setting ': {'ptype': 'Hash', 'required': True},
                         'setting[value] ': {'ptype': 'String',
                                             'required': False}}},
 'smart_class_parameters': {'index': {'environment_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                          'required': False},
                                      'host_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                   'required': False},
                                      'hostgroup_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                        'required': False},
                                      'order ': {'ptype': 'String',
                                                 'required': False},
                                      'page ': {'ptype': 'String',
                                                'required': False},
                                      'per_page ': {'ptype': 'String',
                                                    'required': False},
                                      'puppetclass_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                          'required': False},
                                      'search ': {'ptype': 'String',
                                                  'required': False}},
                            'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                             'required': True}},
                            'update': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                               'required': True},
                                       'smart_class_parameter ': {'ptype': 'Hash',
                                                                  'required': True},
                                       'smart_class_parameter[default_value] ': {'ptype': 'String',
                                                                                 'required': False},
                                       'smart_class_parameter[description] ': {'ptype': 'String',
                                                                               'required': False},
                                       'smart_class_parameter[override] ': {'ptype': "'true' or 'false'",
                                                                            'required': False},
                                       'smart_class_parameter[override_value_order] ': {'ptype': 'String',
                                                                                        'required': False},
                                       'smart_class_parameter[parameter_type] ': {'ptype': "'true' or 'false'",
                                                                                  'required': False},
                                       'smart_class_parameter[path] ': {'ptype': 'String',
                                                                        'required': False},
                                       'smart_class_parameter[validator_rule] ': {'ptype': 'String',
                                                                                  'required': False},
                                       'smart_class_parameter[validator_type] ': {'ptype': 'String',
                                                                                  'required': False}}},
 'smart_proxies': {'create': {'smart_proxy ': {'ptype': 'Hash',
                                               'required': False},
                              'smart_proxy[name] ': {'ptype': 'String',
                                                     'required': True},
                              'smart_proxy[url] ': {'ptype': 'String',
                                                    'required': True}},
                   'destroy': {'id ': {'ptype': 'String', 'required': True}},
                   'import_puppetclasses': {'dryrun ': {'ptype': "'true' or 'false'",
                                                        'required': False},
                                            'environment_id ': {'ptype': 'String',
                                                                'required': False},
                                            'except ': {'ptype': 'String',
                                                        'required': False},
                                            'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                    'required': True},
                                            'smart_proxy_id ': {'ptype': 'String',
                                                                'required': False}},
                   'index': {'page ': {'ptype': 'String', 'required': False},
                             'per_page ': {'ptype': 'String',
                                           'required': False},
                             'type ': {'ptype': 'String', 'required': False}},
                   'refresh': {'id ': {'ptype': 'String', 'required': True}},
                   'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                    'required': True}},
                   'update': {'id ': {'ptype': 'String', 'required': True},
                              'smart_proxy ': {'ptype': 'Hash',
                                               'required': False},
                              'smart_proxy[name] ': {'ptype': 'String',
                                                     'required': False},
                              'smart_proxy[url] ': {'ptype': 'String',
                                                    'required': False}}},
 'smart_variables': {'create': {'smart_variable ': {'ptype': 'Hash',
                                                    'required': False},
                                'smart_variable[default_value] ': {'ptype': 'String',
                                                                   'required': False},
                                'smart_variable[description] ': {'ptype': 'String',
                                                                 'required': False},
                                'smart_variable[override_value_order] ': {'ptype': 'String',
                                                                          'required': False},
                                'smart_variable[puppetclass_id] ': {'ptype': 'number.',
                                                                    'required': False},
                                'smart_variable[validator_rule] ': {'ptype': 'String',
                                                                    'required': False},
                                'smart_variable[validator_type] ': {'ptype': 'String',
                                                                    'required': False},
                                'smart_variable[variable] ': {'ptype': 'String',
                                                              'required': True},
                                'smart_variable[variable_type] ': {'ptype': 'String',
                                                                   'required': False}},
                     'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                         'required': True}},
                     'index': {'host_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                            'required': False},
                               'hostgroup_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                 'required': False},
                               'order ': {'ptype': 'String',
                                          'required': False},
                               'page ': {'ptype': 'String',
                                         'required': False},
                               'per_page ': {'ptype': 'String',
                                             'required': False},
                               'puppetclass_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                   'required': False},
                               'search ': {'ptype': 'String',
                                           'required': False}},
                     'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                      'required': True}},
                     'update': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                        'required': True},
                                'smart_variable ': {'ptype': 'Hash',
                                                    'required': False},
                                'smart_variable[default_value] ': {'ptype': 'String',
                                                                   'required': False},
                                'smart_variable[description] ': {'ptype': 'String',
                                                                 'required': False},
                                'smart_variable[override_value_order] ': {'ptype': 'String',
                                                                          'required': False},
                                'smart_variable[puppetclass_id] ': {'ptype': 'number.',
                                                                    'required': False},
                                'smart_variable[validator_rule] ': {'ptype': 'String',
                                                                    'required': False},
                                'smart_variable[validator_type] ': {'ptype': 'String',
                                                                    'required': False},
                                'smart_variable[variable] ': {'ptype': 'String',
                                                              'required': False},
                                'smart_variable[variable_type] ': {'ptype': 'String',
                                                                   'required': False}}},
 'statistics': {'index': {}},
 'subnets': {'create': {'subnet ': {'ptype': 'Hash', 'required': False},
                        'subnet[dhcp_id] ': {'ptype': 'number.',
                                             'required': False},
                        'subnet[dns_id] ': {'ptype': 'number.',
                                            'required': False},
                        'subnet[dns_primary] ': {'ptype': 'String',
                                                 'required': False},
                        'subnet[dns_secondary] ': {'ptype': 'String',
                                                   'required': False},
                        'subnet[domain_ids] ': {'ptype': 'Array',
                                                'required': False},
                        'subnet[from] ': {'ptype': 'String',
                                          'required': False},
                        'subnet[gateway] ': {'ptype': 'String',
                                             'required': False},
                        'subnet[mask] ': {'ptype': 'String',
                                          'required': True},
                        'subnet[name] ': {'ptype': 'String',
                                          'required': True},
                        'subnet[network] ': {'ptype': 'String',
                                             'required': True},
                        'subnet[tftp_id] ': {'ptype': 'number.',
                                             'required': False},
                        'subnet[to] ': {'ptype': 'String',
                                        'required': False},
                        'subnet[vlanid] ': {'ptype': 'String',
                                            'required': False}},
             'destroy': {'id ': {'ptype': 'number.', 'required': True}},
             'index': {'order ': {'ptype': 'String', 'required': False},
                       'page ': {'ptype': 'String', 'required': False},
                       'per_page ': {'ptype': 'String', 'required': False},
                       'search ': {'ptype': 'String', 'required': False}},
             'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                              'required': True}},
             'update': {'id ': {'ptype': 'number.', 'required': True},
                        'subnet ': {'ptype': 'Hash', 'required': False},
                        'subnet[dhcp_id] ': {'ptype': 'number.',
                                             'required': False},
                        'subnet[dns_id] ': {'ptype': 'number.',
                                            'required': False},
                        'subnet[dns_primary] ': {'ptype': 'String',
                                                 'required': False},
                        'subnet[dns_secondary] ': {'ptype': 'String',
                                                   'required': False},
                        'subnet[domain_ids] ': {'ptype': 'Array',
                                                'required': False},
                        'subnet[from] ': {'ptype': 'String',
                                          'required': False},
                        'subnet[gateway] ': {'ptype': 'String',
                                             'required': False},
                        'subnet[mask] ': {'ptype': 'String',
                                          'required': False},
                        'subnet[name] ': {'ptype': 'String',
                                          'required': False},
                        'subnet[network] ': {'ptype': 'String',
                                             'required': False},
                        'subnet[tftp_id] ': {'ptype': 'number.',
                                             'required': False},
                        'subnet[to] ': {'ptype': 'String',
                                        'required': False},
                        'subnet[vlanid] ': {'ptype': 'String',
                                            'required': False}}},
 'tasks': {'index': {}},
 'template_combinations': {'create': {'config_template_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                              'required': True},
                                      'template_combination ': {'ptype': 'Hash',
                                                                'required': True},
                                      'template_combination[environment_id] ': {'ptype': 'number.',
                                                                                'required': False},
                                      'template_combination[hostgroup_id] ': {'ptype': 'number.',
                                                                              'required': False}},
                           'destroy': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                               'required': True}},
                           'index': {'config_template_id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                                             'required': True}},
                           'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                            'required': True}}},
 'template_kinds': {'index': {'page ': {'ptype': 'String',
                                        'required': False},
                              'per_page ': {'ptype': 'String',
                                            'required': False}}},
 'usergroups': {'create': {'usergroup ': {'ptype': 'Hash',
                                          'required': False},
                           'usergroup[name] ': {'ptype': 'String',
                                                'required': True}},
                'destroy': {'id ': {'ptype': 'String', 'required': True}},
                'index': {'order ': {'ptype': 'String', 'required': False},
                          'page ': {'ptype': 'String', 'required': False},
                          'per_page ': {'ptype': 'String',
                                        'required': False},
                          'search ': {'ptype': 'String', 'required': False}},
                'show': {'id ': {'ptype': 'identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.',
                                 'required': True}},
                'update': {'id ': {'ptype': 'String', 'required': True},
                           'usergroup ': {'ptype': 'Hash',
                                          'required': False},
                           'usergroup[name] ': {'ptype': 'String',
                                                'required': False}}},
 'users': {'create': {'user ': {'ptype': 'Hash', 'required': False},
                      'user[admin] ': {'ptype': "'true' or 'false'",
                                       'required': False},
                      'user[auth_source_id] ': {'ptype': 'Integer',
                                                'required': True},
                      'user[firstname] ': {'ptype': 'String',
                                           'required': False},
                      'user[lastname] ': {'ptype': 'String',
                                          'required': False},
                      'user[login] ': {'ptype': 'String', 'required': True},
                      'user[mail] ': {'ptype': 'String', 'required': True},
                      'user[password] ': {'ptype': 'String',
                                          'required': True}},
           'destroy': {'id ': {'ptype': 'String', 'required': True}},
           'index': {'order ': {'ptype': 'String', 'required': False},
                     'page ': {'ptype': 'String', 'required': False},
                     'per_page ': {'ptype': 'String', 'required': False},
                     'search ': {'ptype': 'String', 'required': False}},
           'show': {'id ': {'ptype': 'String', 'required': True}},
           'update': {'id ': {'ptype': 'String', 'required': True},
                      'user ': {'ptype': 'Hash', 'required': False},
                      'user[admin] ': {'ptype': "'true' or 'false'",
                                       'required': False},
                      'user[auth_source_id] ': {'ptype': 'Integer',
                                                'required': False},
                      'user[firstname] ': {'ptype': 'String',
                                           'required': False},
                      'user[lastname] ': {'ptype': 'String',
                                          'required': False},
                      'user[login] ': {'ptype': 'String', 'required': False},
                      'user[mail] ': {'ptype': 'String', 'required': False},
                      'user[password] ': {'ptype': 'String',
                                          'required': False}}}}